ROOM_SEED_DATA = [
    {
        "room_number": "101",
        "room_type": "Standard Single Room",
        "price": 50,
        "included_guests": 1,
        "capacity": 1,
        "extra_allowed": False,
        "extra_person_fee": 15,
        "description": "A compact private stay for solo travelers with a single bed, minibar, and all essentials.",
    },
    {
        "room_number": "102",
        "room_type": "Standard Double Room",
        "price": 60,
        "included_guests": 2,
        "capacity": 2,
        "extra_allowed": False,
        "extra_person_fee": 15,
        "description": "A practical standard stay with king bed comfort, air conditioning, minibar, and private bathroom.",
    },
    {
        "room_number": "103",
        "room_type": "Standard Twin Room",
        "price": 60,
        "included_guests": 2,
        "capacity": 2,
        "extra_allowed": False,
        "extra_person_fee": 15,
        "description": "A standard twin setup with two single beds, soundproofing, minibar, and a private bathroom.",
    },
    {
        "room_number": "201",
        "room_type": "Deluxe Double Room",
        "price": 65,
        "included_guests": 2,
        "capacity": 3,
        "extra_allowed": True,
        "extra_person_fee": 15,
        "description": "An upgraded double room with more floor space, scenic views, king bed comfort, and polished essentials.",
    },
    {
        "room_number": "202",
        "room_type": "Deluxe Twin Room",
        "price": 65,
        "included_guests": 2,
        "capacity": 3,
        "extra_allowed": True,
        "extra_person_fee": 15,
        "description": "A flexible twin setup with two single beds, a wider room plan, and mountain and city outlooks.",
    },
    {
        "room_number": "203",
        "room_type": "Triple Room",
        "price": 85,
        "included_guests": 3,
        "capacity": 4,
        "extra_allowed": True,
        "extra_person_fee": 15,
        "description": "A practical triple room with three single beds and a layout that works well for small groups.",
    },
    {
        "room_number": "301",
        "room_type": "Suite",
        "price": 105,
        "included_guests": 2,
        "capacity": 3,
        "extra_allowed": True,
        "extra_person_fee": 15,
        "description": "A roomy suite with a separate living area, king bedroom, sofa bed, and more privacy.",
    },
    {
        "room_number": "401",
        "room_type": "Presidential Suite",
        "price": 150,
        "included_guests": 2,
        "capacity": 3,
        "extra_allowed": True,
        "extra_person_fee": 15,
        "description": "The most premium suite with a large king bedroom, living area, sofa bed, and private kitchen.",
    },
]
